from pydantic import BaseModel

class FinancialData(BaseModel):
    IndustryCode: float
    T_2_CashAndDeposits: float
    T_2_NotesReceivable: float
    T_2_AccountsReceivable: float
    T_2_OtherCurrentAssets: float
    T_2_CompletedProjectsAccruedIncome: float
    T_2_ConstructionInProgressExpenses: float
    T_2_Inventory: float
    T_2_OtherCurrentAssets2: float
    T_2_ShortTermLoansReceivable: float
    T_2_CurrentAssets: float
    T_2_AllowanceForDoubtfulAccounts: float
    T_2_TangibleFixedAssets: float
    T_2_IntangibleFixedAssets: float
    T_2_InvestmentsAndOtherAssets: float
    T_2_DeferredAssets: float
    T_2_LongTermLoansReceivable: float
    T_2_FixedAssets: float
    T_2_TotalAssets: float
    T_2_NotesPayable: float
    T_2_AccountsPayable: float
    T_2_ShortTermBorrowings: float
    T_2_AccruedExpenses: float
    T_2_Provisions: float
    T_2_AdvanceReceivedForConstruction: float
    T_2_AdvanceReceived: float
    T_2_OtherCurrentLiabilities: float
    T_2_CurrentLiabilities: float
    T_2_LongTermBorrowings: float
    T_2_OtherNonCurrentLiabilities: float
    T_2_NonCurrentLiabilities: float
    T_2_TotalLiabilities: float
    T_2_CapitalStock: float
    T_2_Reserves: float
    T_2_UndistributedProfitBS: float
    T_2_TotalEquity: float
    T_2_TotalLiabilitiesEquity: float
    T_2_AssetLiabilityError: float
    T_2_DiscountedNotes: float
    T_2_EndorsedNotes: float
    T_2_Sales: float
    T_2_CostOfGoodsSold: float
    T_2_GrossProfit: float
    T_2_SG_AExpenses: float
    T_2_OperatingIncome: float
    T_2_InterestIncome: float
    T_2_OtherNonOperatingIncome: float
    T_2_TotalNonOperatingIncome: float
    T_2_InterestExpense: float
    T_2_OtherNonOperatingExpenses: float
    T_2_TotalNonOperatingExpenses: float
    T_2_OrdinaryIncome: float
    T_2_SpecialGains: float
    T_2_SpecialLosses: float
    T_2_IncomeBeforeTax: float
    T_2_CorporateTax: float
    T_2_NetIncome: float
    T_2_CarryForwardProfit: float
    T_2_InterimDividends: float
    T_2_UndistributedProfitPL: float
    T_2_BSPL_Error: float
    T_2_CarryForwardProfitError: float
    T_2_SpecialDepreciationReserve: float
    T_2_Depreciation: float
    T_1_CashAndDeposits: float
    T_1_NotesReceivable: float
    T_1_AccountsReceivable: float
    T_1_OtherCurrentAssets: float
    T_1_CompletedProjectsAccruedIncome: float
    T_1_ConstructionInProgressExpenses: float
    T_1_Inventory: float
    T_1_OtherCurrentAssets2: float
    T_1_ShortTermLoansReceivable: float
    T_1_CurrentAssets: float
    T_1_AllowanceForDoubtfulAccounts: float
    T_1_TangibleFixedAssets: float
    T_1_IntangibleFixedAssets: float
    T_1_InvestmentsAndOtherAssets: float
    T_1_DeferredAssets: float
    T_1_LongTermLoansReceivable: float
    T_1_FixedAssets: float
    T_1_TotalAssets: float
    T_1_NotesPayable: float
    T_1_AccountsPayable: float
    T_1_ShortTermBorrowings: float
    T_1_AccruedExpenses: float
    T_1_Provisions: float
    T_1_AdvanceReceivedForConstruction: float
    T_1_AdvanceReceived: float
    T_1_OtherCurrentLiabilities: float
    T_1_CurrentLiabilities: float
    T_1_LongTermBorrowings: float
    T_1_OtherNonCurrentLiabilities: float
    T_1_NonCurrentLiabilities: float
    T_1_TotalLiabilities: float
    T_1_CapitalStock: float
    T_1_Reserves: float
    T_1_UndistributedProfitBS: float
    T_1_TotalEquity: float
    T_1_TotalLiabilitiesEquity: float
    T_1_AssetLiabilityError: float
    T_1_DiscountedNotes: float
    T_1_EndorsedNotes: float
    T_1_Sales: float
    T_1_CostOfGoodsSold: float
    T_1_GrossProfit: float
    T_1_SG_AExpenses: float
    T_1_OperatingIncome: float
    T_1_InterestIncome: float
    T_1_OtherNonOperatingIncome: float
    T_1_TotalNonOperatingIncome: float
    T_1_InterestExpense: float
    T_1_OtherNonOperatingExpenses: float
    T_1_TotalNonOperatingExpenses: float
    T_1_OrdinaryIncome: float
    T_1_SpecialGains: float
    T_1_SpecialLosses: float
    T_1_IncomeBeforeTax: float
    T_1_CorporateTax: float
    T_1_NetIncome: float
    T_1_CarryForwardProfit: float
    T_1_InterimDividends: float
    T_1_UndistributedProfitPL: float
    T_1_BSPL_Error: float
    T_1_CarryForwardProfitError: float
    T_1_SpecialDepreciationReserve: float
    T_1_Depreciation: float